#define GETATTR 0
#define OPEN 1
#define READ 2
#define WRITE 3
#define RELEASE 4
#define RENAME 5
#define UNLINK 6
#define RMDIR 7
#define MKDIR 8
#define OPENDIR 9
#define CREATE 10
#define RELEASEDIR 11
#define READDIR 12
#define TRUNCATE 13
#define MKNOD 14
#define UTIME 15
#define LOCK 16
#define HEALTHCHECK 17
#define STORAGE_TRANS_FROM 18
#define STORAGE_TRANS_TO 19